file=open('sample3.txt',"w+")
file.write("This is a sample text file created by w+ mode in file handling and read a string in file.")
position=file.tell()
file.seek(0)
print(f"the position of the cursor is at {position}.")
print(file.read(11))
position1=file.tell()
print(f" after reading file the position of the cursor is at {position1}.")
file.close()