s="Tops Technologies"

print(s)
print(len(s))
print(s.capitalize())
print(s.casefold())
print(s.center(40,"*"))
print(s.count("o"))
print(s.endswith("es"))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("tops 123".isalnum())
print("Tops".isalpha())
print(s.isalpha())
print("123".isnumeric())
print("tops".islower())
print("TOPS".isupper())
print(" ".isspace())
print(s.istitle())
print(s.lower())
print(s.upper())
print("python".title())
print("Hello".replace("l","w"))
print(s.swapcase())

